# Generated by Django 5.2.5 on 2025-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_question_image_question_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_path',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mock_questions/'),
        ),
    ]
