# Generated by Django 5.2.5 on 2025-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_mock_question_mock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes'),
        ),
    ]
