# Generated by Django 5.2.5 on 2025-08-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_mockresult_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockresult',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockresult',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mockresult',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
