# Generated by Django 5.2.5 on 2025-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_infocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='author_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos/'),
        ),
    ]
