# Generated by Django 5.2.5 on 2025-08-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_infocard_author_education_infocard_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocard',
            name='author_education',
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='author_photo',
        ),
    ]
