# Generated by Django 5.2.5 on 2025-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_infocard_author_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='authors/')),
            ],
        ),
    ]
