# Generated by Django 5.2.5 on 2025-08-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
