# Generated by Django 5.2.5 on 2025-08-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='authors/')),
            ],
        ),
    ]
