# Generated by Django 5.2.5 on 2025-09-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_studymaterial_delete_infocard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='description',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='study_materials/'),
        ),
        migrations.CreateModel(
            name='StudyMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='study_material_items/')),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.studymaterial')),
            ],
        ),
    ]
