# Generated by Django 5.2.5 on 2025-09-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gmail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='taluk_name',
            field=models.CharField(max_length=50),
        ),
    ]
