# Generated by Django 5.2.5 on 2025-09-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_gmail_profile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
