# Generated by Django 5.2.5 on 2025-09-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_profile_college_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
