# Generated by Django 5.2.5 on 2025-09-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
