# Generated by Django 5.2.5 on 2025-09-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_profile_address_alter_profile_whatsapp_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
