# Generated by Django 5.2.5 on 2025-09-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_mock_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='course',
            field=models.CharField(choices=[('agri_quota', 'Agriculture Quota Practical Exam'), ('cuet_ug_icar', 'CUET UG Agriculture – ICAR')], default='agri_quota', max_length=20, verbose_name='Course'),
        ),
    ]
